import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import type { StarMeta } from '../src/data/types';
import { deriveStarMotionModel } from '../src/core/stars';
import { cachedStarEpoch, writeStarDirectionBuffer, STAR_CACHE_DIRECTION_BOUND_ARCSEC, STAR_FLOAT32_DIRECTION_BOUND_ARCSEC, STAR_MOTION_CACHE_BOUND_ARCSEC } from '../src/render/StarDirectionBuffer';

interface IndependentRecord {
  id: string; motionModel: 'linear-space' | 'tangent'; p0: [number, number, number]; vPerJulianYear: [number, number, number];
  endpointPadded15DayCacheArcsecBound: number;
}
// Generated by the independent source-scalar audit, not any production motion helper.
const records: IndependentRecord[] = JSON.parse(readFileSync(new URL('../qa/science-reference-prep/motion-cache-bound-records.json', import.meta.url), 'utf8'));
// Node cannot load Vite's ?raw imports. Rehydrate the unchanged complete metadata,
// without implementing any eligibility or exception policy in this test adapter.
const metadata: unknown[][] = JSON.parse(readFileSync(new URL('../assets/runtime/star-meta.json', import.meta.url), 'utf8'));
const catalog = { stars: metadata.map((r, index): StarMeta => ({ index, id: r[0] as StarMeta['id'], hygId: r[1] as number, hip: r[2] as number | null,
  raHours: r[3] as number, decDeg: r[4] as number, magnitude: r[5] as number, colorIndex: r[6] as number | null,
  nameEn: (r[7] as string | null) ?? undefined, nameZh: (r[8] as string | null) ?? undefined, aliases: r[9] as string[],
  pmRaMasYr: r[10] as number, pmRaCosDecMasYr: r[10] as number, pmDecMasYr: r[11] as number, qualityFlags: r[12] as number,
  distancePc: r[13] as number | null, radialVelocityKmS: r[14] as number | null, spaceVelocityEqjPcYr: r[15] as StarMeta['spaceVelocityEqjPcYr'],
  variableName: r[16] as string | null, variableMagnitudeRange: [r[17] as number | null, r[18] as number | null], component: r[19] as number,
  componentPrimaryHygId: r[20] as number, constellationId: r[21] as string,
})) };
const byId = new Map(records.map(record => [record.id, record]));
const startUt = 990574.5 - 2451545, endUt = 3182395.5 - 2451545;
const dates = [startUt, startUt + 15, -1_000_000, -500_000, -15, 0, 15, 5000, 10000, 100_000, endUt - 15, endUt - 5.5, endUt];
function oracle(record: IndependentRecord, ut: number): [number, number, number] {
  const years = ut / 365.25;
  const p = record.p0.map((value, axis) => value + years * record.vPerJulianYear[axis]!) as [number, number, number];
  const length = Math.hypot(...p);
  return p.map(value => value / length) as [number, number, number];
}
function separationArcsec(a: readonly number[], b: readonly number[]): number {
  const cross = [a[1]! * b[2]! - a[2]! * b[1]!, a[2]! * b[0]! - a[0]! * b[2]!, a[0]! * b[1]! - a[1]! * b[0]!];
  return Math.atan2(Math.hypot(...cross), a.reduce((sum, value, axis) => sum + value * b[axis]!, 0)) * 180 / Math.PI * 3600;
}

test('both production buffer types receive all 8921 complete records and the sole core motion policy', () => {
  assert.equal(catalog.stars.length, 8921); assert.equal(records.length, catalog.stars.length);
  const counts = { 'linear-space': 0, tangent: 0 };
  for (const star of catalog.stars) {
    const actual = deriveStarMotionModel(star), expected = byId.get(star.id)!;
    assert.equal(actual.model, expected.motionModel, star.id); counts[actual.model]++;
    assert.equal(actual.fallbackReasons.length === 0, actual.model === 'linear-space', star.id);
  }
  assert.deepEqual(counts, { 'linear-space': 8296, tangent: 625 });
});

test('new core all-catalog buffers match independent source-scalar directions and retain a sub-arcsecond combined cache bound', () => {
  const buffer32 = new Float32Array(catalog.stars.length * 3), buffer64 = new Float64Array(buffer32.length);
  const maxima = { scalarOracleArcsec: 0, float32Arcsec: 0, cachedMotionArcsec: 0, combinedArcsec: 0 };
  const worst: Record<string, { id: string; ut: number }> = {};
  const update = (key: keyof typeof maxima, value: number, id: string, ut: number) => { if (value > maxima[key]) { maxima[key] = value; worst[key] = { id, ut }; } };
  for (const ut of dates) {
    const epoch = cachedStarEpoch(ut);
    assert.ok(Math.abs(ut - epoch) <= 15);
    writeStarDirectionBuffer(catalog.stars, epoch, buffer32);
    writeStarDirectionBuffer(catalog.stars, ut, buffer64);
    for (const star of catalog.stars) {
      const index = star.index * 3, exact = [...buffer64.subarray(index, index + 3)], uploaded = [...buffer32.subarray(index, index + 3)];
      const independent = byId.get(star.id)!, expectedExact = oracle(independent, ut), expectedCache = oracle(independent, epoch);
      const scalar = separationArcsec(exact, expectedExact), quantized = separationArcsec(uploaded, expectedCache);
      const motion = separationArcsec(expectedExact, expectedCache), combined = separationArcsec(uploaded, expectedExact);
      assert.ok(scalar < 1e-7, `${star.id}: scalar=${scalar}`);
      assert.ok(quantized <= STAR_FLOAT32_DIRECTION_BOUND_ARCSEC, `${star.id}: Float32=${quantized}`);
      assert.ok(motion <= independent.endpointPadded15DayCacheArcsecBound + 1e-7, `${star.id}: motion=${motion}`);
      assert.ok(combined <= STAR_CACHE_DIRECTION_BOUND_ARCSEC, `${star.id}: combined=${combined}`);
      uploaded.forEach((value, axis) => assert.ok(Number.isFinite(value) && Math.abs(value - expectedCache[axis]!) <= 2 ** -25 + 2e-15));
      update('scalarOracleArcsec', scalar, star.id, ut); update('float32Arcsec', quantized, star.id, ut);
      update('cachedMotionArcsec', motion, star.id, ut); update('combinedArcsec', combined, star.id, ut);
    }
  }
  assert.ok(STAR_MOTION_CACHE_BOUND_ARCSEC >= Math.max(...records.map(record => record.endpointPadded15DayCacheArcsecBound)));
  mkdirSync('qa/m5b-render', { recursive: true });
  writeFileSync('qa/m5b-render/star-buffer-report.json', JSON.stringify({ dates, samples: dates.length * catalog.stars.length, maxima, worst,
    bounds: { motionArcsec: STAR_MOTION_CACHE_BOUND_ARCSEC, normalizedFloat32Arcsec: STAR_FLOAT32_DIRECTION_BOUND_ARCSEC, combinedArcsec: STAR_CACHE_DIRECTION_BOUND_ARCSEC },
    evidence: 'Actual production writeStarDirectionBuffer with all complete StarMeta records, Float64 Canvas and Float32 WebGL buffers; independent fixed-source p0/v directions.',
    limits: 'Samples validate production formula/buffers; analytic all-time motion bound comes from the independent source-scalar audit. Bounds exclude catalog measurement errors, unimplemented aberration/parallax and pixel projection.' }, null, 2));
});
