// Rebuild the brochure from real application captures. Requires local Chrome.
import { chromium } from '@playwright/test';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const files = ['overview-ground','overview-earth','overview-celestial','overview-horizon','feature-moon','feature-milky-way'];
const images = Object.fromEntries(await Promise.all(files.map(async name => [name, `data:image/png;base64,${(await readFile(`media/screenshots/${name}.png`)).toString('base64')}`])));
const img = (name, cls='') => `<img class="${cls}" src="${images[name]}" alt="${name}">`;
const footer = n => `<footer><span>SKY SIMULATOR / 三维全景夜空</span><span>公开预览版 · v0.1.0</span><span>0${n} / 05</span></footer>`;
const html = `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>Sky Simulator · 三维全景夜空</title><style>
@page{size:400mm 250mm;margin:0}*{box-sizing:border-box}body{margin:0;font-family:"Microsoft YaHei","Noto Sans CJK SC",sans-serif;color:#eaf2f7;background:#07111c}section{width:1512px;height:945px;position:relative;overflow:hidden;page-break-after:always;background:#07111c;padding:60px 66px}section:last-child{page-break-after:auto}h1,h2,h3,p{margin:0}h1{font-size:76px;line-height:1.22;font-weight:600;letter-spacing:2px}h2{font-size:42px;font-weight:500;line-height:1.35}h3{font-size:25px;font-weight:500}p{font-size:22px;line-height:1.8;color:#b6cad6}.eyebrow{font:16px Arial,sans-serif;letter-spacing:5px;color:#6ee0da;margin-bottom:24px}.line{width:58px;height:3px;background:#6ee0da;margin:28px 0}.small{font-size:15px;line-height:1.8;color:#91a8b7}.muted{color:#91a8b7}footer{position:absolute;bottom:27px;left:66px;right:66px;display:flex;justify-content:space-between;color:#7993a5;font-size:12px;letter-spacing:1px;border-top:1px solid #29404f;padding-top:15px}img{display:block;object-fit:contain}.cover{padding-top:56px}.cover>.hero{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.cover:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(3,12,21,.94),rgba(3,12,21,.62) 44%,rgba(3,12,21,.06)),linear-gradient(0deg,#07111c,transparent 28%)}.cover .copy{position:relative;z-index:1;width:820px;margin-top:130px}.cover footer{z-index:2}.cover h1 span{display:block;font-size:26px;letter-spacing:7px;color:#8cb9cd;margin-top:20px}.cover p{margin-top:38px;max-width:620px;font-size:25px}.tag{display:inline-block;border:1px solid #426277;padding:9px 15px;margin:30px 10px 0 0;color:#b6d7e7;font-size:17px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:28px}.card{background:#0c1b29;border:1px solid #223949;position:relative;height:302px;overflow:hidden}.card img{width:100%;height:252px;object-fit:cover}.card p{font-size:18px;line-height:50px;padding:0 20px}.grid-title{display:flex;align-items:end;justify-content:space-between}.grid-title p{font-size:18px;width:500px}.split{display:grid;grid-template-columns:960px 1fr;gap:38px;margin-top:35px}.split img{width:960px;height:615px;object-fit:contain;background:#020609;border:1px solid #233b49}.split .text{padding-top:24px}.split p{font-size:20px;margin:15px 0 25px}.feature-image{width:100%;height:590px;object-fit:contain;background:#030609;margin-top:25px;border:1px solid #223949}.feature-copy{display:flex;justify-content:space-between;margin-top:20px;gap:55px}.feature-copy p{font-size:20px;flex:1}.download{display:grid;grid-template-columns:610px 1fr;gap:55px;margin-top:30px}.download .preview{width:100%;height:390px;object-fit:cover;border:1px solid #29404f}.step{border-left:2px solid #5dc8c3;padding-left:20px;margin:28px 0}.step p{font-size:19px;margin-top:7px}.url{font:19px Arial,sans-serif;color:#6ee0da;word-break:break-all}.credits{font-size:13px;line-height:1.8;color:#809aaa;margin-top:22px}a{color:#6ee0da;text-decoration:none}
</style><body>
<section class="cover">${img('overview-ground','hero')}<div class="copy"><div class="eyebrow">EXPLORE THE SKY. UNDERSTAND THE MOTION.</div><h1>三维全景夜空<span>SKY SIMULATOR</span></h1><div class="line"></div><p>从脚下的地平线，到包围地球的天球。<br>在同一时刻，看懂天空的四种视角。</p><span class="tag">四视图联动</span><span class="tag">日月与历法</span><span class="tag">离线可用</span><p class="small" style="font-size:16px;margin-top:30px">真实应用截图 · 天文学教学与自主探索</p></div>${footer(1)}</section>
<section><div class="eyebrow">ONE SKY / FOUR PERSPECTIVES</div><div class="grid-title"><h2>换一个位置，理解同一片天空</h2><p>四种视图共用时间、地点和天文计算。<br>切换视角时，保留选择与各自相机。</p></div><div class="grid"><div class="card">${img('overview-ground')}<p>01 地表夜空 / 站在观测者的位置</p></div><div class="card">${img('overview-earth')}<p>02 太空视角 / 看见地球受光与昼夜</p></div><div class="card">${img('overview-celestial')}<p>03 外部天球 / 理解恒星的空间方向</p></div><div class="card">${img('overview-horizon')}<p>04 地平天球 / 分清天顶、地平与地轴</p></div></div><p class="small" style="margin-top:20px">画面来自当前公开预览构建；教学示意与当地真实可见性在界面中分别标注。</p>${footer(2)}</section>
<section><div class="eyebrow">MOON / TIME / CALENDAR</div><h2>把月相与时间，放在一起观察</h2><div class="split">${img('feature-moon')}<div class="text"><h3>月相放大镜</h3><p>截图主月盘为20×教学放大，非真实角径；与放大镜共用同一时刻与月面姿态。</p><h3>跳转到天文事件</h3><p>搜索相邻四月相，查看太阳、月球和所选恒星的当地日升落。</p><h3>跨越日期与时区</h3><p>支持正向、反向和实时播放；保留时区与农历日界的不同约定。</p><p class="small">农历支持1901-2100年；部分未来年份的不确定性在应用内标示。地平下的月球教学图不表示当前可见。</p></div></div>${footer(3)}</section>
<section><div class="eyebrow">STARS / MILKY WAY / VISIBILITY</div><h2>看见星空，也理解看不见的原因</h2>${img('feature-milky-way','feature-image')}<div class="feature-copy"><p>真实星表与88星座，支持中文名称、英文名和编号搜索。选择、定位与连线，让探索有迹可循。</p><p>银河、大气与定性光污染模拟共同展示对比度变化。不是实时天气、实测天空亮度或随机生成的星空。</p></div>${footer(4)}</section>
<section><div class="eyebrow">GET STARTED / KEEP EXPLORING</div><h2>打开浏览器，就能开始探索</h2><div class="download"><div><div class="step"><h3>下载桌面离线版</h3><p>在GitHub Releases下载单HTML，使用桌面Chrome或Edge直接打开。</p></div><div class="step"><h3>保存你的教学场景</h3><p>导入、导出场景JSON；保存时间、地点、视图和选中对象，便于课堂复现。</p></div><div class="step"><h3>部署Web版，或继续开发</h3><p>完整源码与Web发行包一并提供；Web版支持缓存后离线使用。</p></div><a class="url" href="https://github.com/Ray8mu34/Sky-Simulator">github.com/Ray8mu34/Sky-Simulator</a><p class="small" style="margin-top:22px">v0.1.0为公开预览版。真实移动设备与Safari尚未完整验证；Firefox存在一次未复现的交互超时。详细范围见仓库发行说明。</p></div><div>${img('overview-horizon','preview')}<h3 style="margin-top:22px">有来源的天空，有边界的承诺</h3><p class="credits">自有代码：MIT · Ray8mu34<br>恒星：HYG v4.1；星座资料：Stellarium Western / Chinese（CC BY-SA 4.0）。<br>银河、地球、月球图像：NASA相关公开数据产品。历法依赖与其他资产按原许可保留署名。具体来源、版本和许可见仓库 assets/licenses 与 assets-manifest.json。<br><br>宣传画面全部来自应用实拍，无AI生成星图；该资料不构成第三方机构对项目的认可。</p></div></div>${footer(5)}</section>
</body></html>`;
await mkdir('tmp/pdfs', { recursive:true });
await mkdir('media', { recursive:true });
const sourcePath = resolve('tmp/pdfs/overview.html');
await writeFile(sourcePath, html);
const browser = await chromium.launch({ channel:'chrome', headless:true });
try {
  const page = await browser.newPage();
  await page.goto(pathToFileURL(sourcePath).href);
  await page.evaluate(() => document.fonts.ready);
  await page.pdf({ path:'media/Sky-Simulator-Overview.pdf', printBackground:true, preferCSSPageSize:true });
} finally { await browser.close(); }
console.log('media/Sky-Simulator-Overview.pdf');
